import pandas as pd 
from pathlib import Path

from clean_data import clean_dataset
from normalizing_df import normalize_data
from  descriptive_statistics import graph_distributions_treated_vs_not, graph_soft_distributions_treated_vs_not, graph_heatmap_corr_cov
from placebo_test import placebo_testing
from normalizing_df import normalize_data